### ISSUE TITLE
Flex employee suffix credentials horizontally

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/particle#175]
https://clouddev.utc.edu/health-education-and-professional-studies/school-of-nursing/faculty-and-staff/faculty
![Screen Shot 2021-02-09 at 1 24 35 PM](https://user-images.githubusercontent.com/39039024/107409448-2e789000-6ada-11eb-8281-3cd435d033e1.png)
https://clouddev.utc.edu/health-education-and-professional-studies/physical-therapy/faculty-and-staff
![Screen Shot 2021-02-09 at 1 25 41 PM](https://user-images.githubusercontent.com/39039024/107409593-5667f380-6ada-11eb-807d-9860813c6939.png)

**Comment by bmartinez287** [comment]
Can we flex the suffix credentials horizontally for the default view mode? It looks good for the other but for the vertical cards the other flows better. Plus it be ideal if we can save some space on the pages that have many faculty members.

**Comment by bmartinez287** [comment]
Related #173

**Comment by bmartinez287** [comment]
Related to: UTCWeb/utccloud#1434

**Comment by brittrich** [comment]
@bmartinez287 when I update develop in utccloud repo and import the config on the develop branch, I do see these as horizontal...which I agree with you, looks alot better.

<img width="839" alt="Screen Shot 2021-02-09 at 9 53 08 PM" src="https://user-images.githubusercontent.com/50490141/107458088-5f2fe800-6b21-11eb-88db-f65ad8aea20c.png">

<img width="848" alt="Screen Shot 2021-02-09 at 10 01 04 PM" src="https://user-images.githubusercontent.com/50490141/107458604-6c010b80-6b22-11eb-85d0-8213417e4f6f.png">

Did I goof something up in the PR that made this change not make it to clouddev? Maybe I didn't add the styles correctly?
https://github.com/UTCWeb/utccloud/pull/1439

**Comment by brittrich** [comment]
To confirm, I do see the style change happening in this particle file in develop. So, I'm sure it's something I didn't do right on compiling and adding the styles to the PR above.

**Comment by bmartinez287** [comment]
There's a reason that could happen.
Steps when merging a PR:

- Switch from name branch back to particle develop branch
- **Wait 2 to 4 min for travis to deploy and compile your branch. [skip travis] Deploying Compiled Assets [skip travis-ci]**
- Add that particle hash into your utcccloud branch.

You might have skipped for the assets to compile which meant the css file reached develop but it was not included in the app.css bundle.

**Comment by bmartinez287** [comment]
So i think what i described above is what happen because Steven merged another PR and that corrected the missing style change. @brittrich
