### ISSUE TITLE
By the numbers block. stats

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/particle#179]
![popularslider item](https://user-images.githubusercontent.com/39039024/108655228-4adbdb80-748f-11eb-8a24-917e7dfc8f99.PNG)
https://michiganross.umich.edu/
https://haslam.utk.edu/

We need to figure out a component like this one. 
I'm sure the departments and colleges would love it.

Additionally, a way of making this type of page would be nice.

https://michiganross.umich.edu/about/key-facts

**Comment by bmartinez287** [comment]
![Screen Shot 2021-05-11 at 3 47 25 PM](https://user-images.githubusercontent.com/39039024/117875507-3e864400-b270-11eb-922c-4109e267f67d.png)

**Comment by bmartinez287** [comment]
@brittrich ideas, on how to layout this type of information would be nice. As well as prototyping how to handle that type of data.

**Comment by brittrich** [comment]
Happy to look at it.
