### ISSUE TITLE
Update input button styles in particle

### ISSUE THREAD

**Issue by brittrich** [UTCWeb/particle#187]
With tailwind enabled button styles on form inputs look like:

<img width="309" alt="Screen Shot 2021-03-01 at 10 36 49 PM" src="https://user-images.githubusercontent.com/50490141/109593481-0ed3f680-7adf-11eb-8a0d-169acc175fcc.png">

@bmartinez287 @darkbluewalrus what if I went ahead and subbed in our standard primary and secondary button classes in the _input.twig atom element? 
<img width="1010" alt="Screen Shot 2021-03-01 at 10 39 11 PM" src="https://user-images.githubusercontent.com/50490141/109593832-b3eecf00-7adf-11eb-8e37-e98ed61e590e.png">

I could add it to a PR I'm working on where this button shows in the unified directory view. Side note...not sure how to edit that file? There are two, one in "dist" and one in "source." Do I edit the "source" and then compile to the "dist"? Do I commit both or just the "source"?

**Comment by bmartinez287** [comment]
You only have to change it on src. Don’t commit the dist one as Travis will
take care of that one. Sounds good to me just make sure to double know it
as that be a site wide change.

**Comment by bmartinez287** [comment]
![Screen Shot 2021-03-02 at 2 29 30 PM](https://user-images.githubusercontent.com/39039024/109709378-68353780-7b6a-11eb-88dc-f2a3f118eacb.png)
It looks like the table block is also impacted by it.

**Comment by bmartinez287** [comment]
http://local.utccloud.com/communications-and-marketing/social-media/social-media-application-form
![Screen Shot 2021-03-02 at 3 23 32 PM](https://user-images.githubusercontent.com/39039024/109710121-4b4d3400-7b6b-11eb-9451-ee4863a1825c.png)
That's quite the global style.

**Comment by brittrich** [comment]
Agreed, definitely global! I was thinking just catching the color style for the button (not updated the main button class-just the color class). Basically, the bright blue is new for !important particle so I wondered if we wanted to fix this. It was light grey before.

From button-primary to btn--navy. Make it the dark blue? Or we could go with .btn--lightblue if we wanted to use a more muted style (which is closer to what it was before particle !important).

.btn--lightblue,
.btn-light {
  @apply bg-gray-300;
  @apply text-utc-new-blue-500;
}

.btn--navy,
.btn-primary,
.btn-dark {
  @apply bg-utc-new-blue-500;
  @apply text-white;
}

**Comment by bmartinez287** [comment]
Due to our users being used to the old one, I think something closer to what we had before might make sense. However, style-wise I will rely on your judgement for that one. Do you have a preference? What seems more modern and appealing?

**Comment by brittrich** [comment]
Light blue will probably be closest. I'll do a draft PR just for this so it can be reviewed separately since the change is so global.

For reference, Pre Particle:

<img width="1010" alt="Screen Shot 2021-03-03 at 6 10 47 AM" src="https://user-images.githubusercontent.com/50490141/109797393-678eb680-7be7-11eb-9978-00e19dd4b85d.png">
