### ISSUE TITLE
Banner Block

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/particle#192]
Fields:
Image field: The image field should behave similar to the image block but provide the option for text overlay.
Title field: Similar to cards. A unique field for that image description
Description: Additional text that can be added under the image.
Read more button or styled link: A link that can reference the news room article or feature element if needed.

![Screen Shot 2021-03-17 at 12 18 02 PM](https://user-images.githubusercontent.com/39039024/111503685-597b8280-871d-11eb-9a49-91b94e886db0.png)
![Screen Shot 2021-03-17 at 12 37 19 PM](https://user-images.githubusercontent.com/39039024/111503900-8b8ce480-871d-11eb-9158-6ef0f1cdc8a8.png)
https://uiowa.edu/
![Screen Shot 2021-03-17 at 12 40 46 PM](https://user-images.githubusercontent.com/39039024/111504474-1372ee80-871e-11eb-8c3a-412b6bf3e99b.png)
https://www.nd.edu/

@brittrich @MegShad -> The items above have a description of the fields that I'm taking into consideration for a banner type block and some samples.

**Comment by bmartinez287** [comment]
The Notre dame one is an interesting one as it points to a highlighted news article and it plays around with the foreground.
I'm trying to gather the most useful fields from our current blocks and find how to this block flexible yet elegant and easy to use.
@brittrich if you have some ideas or feedback feel free to add them here.

**Comment by bmartinez287** [comment]
![Screen Shot 2021-03-17 at 2 04 19 PM](https://user-images.githubusercontent.com/39039024/111515997-d14faa00-8729-11eb-962e-322fcba70053.png)https://www.utoronto.ca/

**Comment by bmartinez287** [comment]
![Screen Shot 2021-03-17 at 2 06 24 PM](https://user-images.githubusercontent.com/39039024/111516194-03f9a280-872a-11eb-8437-159b09dc0f6e.png)
https://www.ua.edu/

**Comment by brittrich** [comment]
@bmartinez287 is this a single static image (not a rotation of images)?

This seems pretty straightforward to me. The most annoying/tricky part might be getting it to span full width. I'm curious whether we can create it with some sort of note that it should be used in full container width layouts? Otherwise, we are looking at negative margin.

Other Qs:

- Would you want a standard button style? Or, allow for the user to select what type of button?
- One button max?
- Options to center/left/right all the elements...or just keep it standard (probably center)?
- Options to adjust the height of it?
- Option to adjust font size? I could see an argument for a title banner vs. a call out vs. an article header (like the examples above).
- What ideal purpose does it serve on the site? (e.g. primarily on landing pages, news areas, etc.)

**Comment by brittrich** [comment]
Also, I think this would be a pretty easy/quick next thing for me to work on if there is a desire (unless someone else already is). After I get the profile styles done up to a point I'll likely pass that off to Steven for feedback. While he reviews I can take a look at this.

**Comment by bmartinez287** [comment]
Layout builder allows the container to be fluid in which case it would span the whole width. Ideally, we can take advantage of that and make this something that can be a top banner or one in the body of a page.

Would you want a standard button style? Or, allow for the user to select what type of button?
Good question probably a dropdown with a taxonomy selection would be ideal so we could start with 2 or 3 styles and add if needed. The style should help accommodates for different backgrounds. However, i like how the notre dame one avoids issue by having the text on the side.
One button max?
for now yes, we could always use the CKEditor field to add more if needed.
Options to center/left/right all the elements...or just keep it standard (probably center)?
the options would be great although I was thinking more as in view modes. The options would be more for centered text on image and how high or low to position it.
Options to adjust the height of it?
not sure
Option to adjust font size? I could see an argument for a title banner vs. a call-out vs. an article header (like the examples above).
sounds good
What ideal purpose does it serve on the site? (e.g. primarily on landing pages, news areas, etc.)
The ideal purpose of it is to replace our current gallery on the UTC homepage. So this will take the place of the 3 image gallery on utc.edu. Once we make it flexible it could go on any landing type page and in the body if is contained within a container. idk if that makes sense.

**Comment by bmartinez287** [comment]
Primarily I'm the one working on it but It be better to collaborate on it. Our goal is for the main homepage to showcase as many reusable components as we can. I figure I start collecting some info and samples to get a better idea of the requirements and expected results.

**Comment by bmartinez287** [comment]
Also, it is a static image for now. We may do another block later for video banners and maybe gallery ones who knows.

**Comment by bmartinez287** [comment]
![Screen Shot 2021-03-19 at 10 09 32 AM](https://user-images.githubusercontent.com/39039024/111793149-5b6b5000-889b-11eb-88fe-05b6a784f614.png)
utk.edu 
I just notice UTK is basically the same as ND except for they flipped the image to the other side.

**Comment by bmartinez287** [comment]
@brittrich as time allows if you could check out the latest version of particle and share some thoughts on how we could improve the current interation of the UTC Hero that be great!
Right now, from my perspective, the biggest challenge is to find what type of background design or image style to use with it and how an editor could rotate through predetermined options. That said, I'm sure you could catch other insights that I may be overlooking. It be great to have feedback and input on how to make it better both in practice and in design. 
Let me know.

**Comment by bmartinez287** [comment]
<img width="1678" alt="Screen Shot 2021-04-01 at 9 28 35 PM" src="https://user-images.githubusercontent.com/39039024/113370222-4b3e8080-9331-11eb-99c1-0d3d948447c5.png">
<img width="1635" alt="Screen Shot 2021-04-01 at 9 25 56 PM" src="https://user-images.githubusercontent.com/39039024/113370229-509bcb00-9331-11eb-8994-ac59bd67db67.png">
I need to adjust the zoom level for 100% on high res screens.

**Comment by bmartinez287** [comment]
120rem and 30m rem seem to perform better at 2xl level.

**Comment by bmartinez287** [comment]
https://new.utc.edu/node/34701
https://cloudtest.utc.edu/node/34701

**Comment by brittrich** [comment]
I think this is done, but feel free to reopen if I'm wrong.
