### ISSUE TITLE
Cards image cropping

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/particle#240]
We need to enable different view modes to UTC cards to allow for more granular control on how those cards look.
![Screen Shot 2021-05-26 at 10 40 09 AM](https://user-images.githubusercontent.com/39039024/119680305-0d307b00-be0f-11eb-94fd-9f6ed7673b31.png)

We have a request to either provide more views modes or provide section editors with image ration and resolutions that work well with utc cards.

@brittrich we probably should look into this, maybe add view modes as an option for the cards.

**Comment by bmartinez287** [comment]
https://utcwebdev.atlassian.net/browse/UWR-2520

**Comment by brittrich** [comment]
Hey @bmartinez287, apologies, I missed this notification somehow! I'll get started on this. I agree, we could do a view mode, or add a field that allows them to select cropping vs. non-cropping with a recommended image size. I think to get rid of autocrop we need to require a standard image size to accomplish alignment, right? Are folks open to that?

**Comment by bmartinez287** [comment]
No worries. I think both would be good. Some of our section editors are graphic designers and they started asking about it. Either to have an extra option or to get an image size. The image size subject is a bit tricky because it should be one that's as multipurpose as one can be. It be ideal if images can be used and reused as much as possible.

**Comment by brittrich** [comment]
> No worries. I think both would be good. Some of our section editors are graphic designers and they started asking about it. Either to have an extra option or to get an image size. The image size subject is a bit tricky because it should be one that's as multipurpose as one can be. It be ideal if images can be used and reused as much as possible.

Yeah, I was just testing it out a bit more, 720 x480 works well without cropping...but you are right that limits use in other places to a degree. I'll test more thoroughly tomorrow night, but I'm guessing we can scale that up. I'll focus on optimal image size in some testing first.

**Comment by brittrich** [comment]
Hey @bmartinez287, I'm working on fixing the cropping for wide cards after chatting with Bridget a bit, and looking at this at the same time. I think we can recommend 900 x 600 or 600 x 900 for thumbnail card images (although the 720 x 480 images coming over from the old website work just fine). I'll look at the best way to add this info to the card image fields.

But, on looking back on the original ticket here, can you point me to a page in this part of the site where she is having issues with the card images? I see a lot of images in use here (http://local.utccloud.com/enrollment-management-and-student-affairs/new-student-and-family-programs), but they aren't in cards. I wonder if the issue she is having is actually related to sizing/adding images through the image block or in the text? Or, maybe she abandoned the cards after she couldn't get them working?

Just wanted to be sure we were getting at the root of her issue, but either way adding a sizing recommendation for the card images will be helpful.

**Comment by bmartinez287** [comment]
https://new.utc.edu/enrollment-management-and-student-affairs/veteran-student-services
![veteranservices](https://user-images.githubusercontent.com/39039024/120907508-af2e3f80-c627-11eb-8edb-bba638a6674c.PNG)
![veteranservicesipadpro](https://user-images.githubusercontent.com/39039024/120907520-ca994a80-c627-11eb-8ce7-b1b80ebb18eb.PNG)

That was the one she was using as an example.
@brittrich

**Comment by brittrich** [comment]
> https://new.utc.edu/enrollment-management-and-student-affairs/veteran-student-services
> ![veteranservices](https://user-images.githubusercontent.com/39039024/120907508-af2e3f80-c627-11eb-8edb-bba638a6674c.PNG)
> ![veteranservicesipadpro](https://user-images.githubusercontent.com/39039024/120907520-ca994a80-c627-11eb-8ce7-b1b80ebb18eb.PNG)
> 
> That was the one she was using as an example.
> @brittrich

Thanks, Bernardo! Those were Bridgets examples, right? I was also trying to find anything about the image issues April Cox was mentioning at the top of this issue thread...or is this the same as what Bridget posted? If it's the same, just disregard. :)

**Comment by bmartinez287** [comment]
https://new.utc.edu/enrollment-management-and-student-affairs/new-student-and-family-programs/orientation/parent-and-family
That page was the one April made a ticket about. It seems like she found out about the height 100%. lol.
Good thing we are not switching that or else she probably opens a new one.
<img width="716" alt="Screen Shot 2021-06-05 at 9 39 02 PM" src="https://user-images.githubusercontent.com/39039024/120909774-8bc6bd00-c646-11eb-9e95-d43c2d6a760e.png">
<img width="746" alt="Screen Shot 2021-06-05 at 9 39 09 PM" src="https://user-images.githubusercontent.com/39039024/120909775-8ec1ad80-c646-11eb-80ea-ef8ca4f50d4c.png">
<img width="656" alt="Screen Shot 2021-06-05 at 9 39 21 PM" src="https://user-images.githubusercontent.com/39039024/120909776-908b7100-c646-11eb-8d78-2c7a5ef43636.png">

I suggested she gets rid of the art on top of the images and it seems like she did, but she was struggling with people faces.


https://clouddev.utc.edu/enrollment-management-and-student-affairs/new-student-and-family-programs/orientation/parent-and-family
cloud dev shows the original images without her hacking them. @brittrich

**Comment by brittrich** [comment]
Thanks, @bmartinez287 that's what I was curious about! It looks to me like she figured out what the optimal size was and worked from there...the images in prod have a lot more clarity as well. Related to this, I've got a possible add on to the config for the cards that I can do a PR for (with the new "no crop" field from https://github.com/UTCWeb/particle/pull/259) if we think this will be helpful. It suggests a preferred image size for the thumbnail cards. 

<img width="914" alt="Screen Shot 2021-06-06 at 10 10 16 PM" src="https://user-images.githubusercontent.com/50490141/120950494-e3cbf500-c714-11eb-8485-36945b4258f1.png">

It may be confusing to not offer a similar description for wide card image sizes? But, honestly, for the wide cards there just isn't a preferred size, the cropping is so variable depending on whether its one card, two cards, screen size, etc. But, the new "no crop" checkbox will help provide another option for folks.

Add in @UTCbridget in case she has an opinion on this as well.

**Comment by bmartinez287** [comment]
I think the permissions are set so all of us could add people. I just added her but I believe you should be able to.
Yeah, go ahead and create that PR. Maybe make a note that for the wide card the size varies, some type of disclosure.
tks

**Comment by brittrich** [comment]
Yes, I can add her. Sorry, haha, I mean't "Adding in" when I @ signed her.

Will do, I'll try to add something short and sweet on the wide card sizing as well.
