### ISSUE TITLE
Address image/logo sizing issue in cards

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#252]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'https://new.utc.edu/enrollment-management-and-student-affairs/veteran-student-services'
2. Scroll down to 'Veteran Peer Menotoring Program'
3. See that the image width is too large for the div.

**Expected behavior** 
Image should fit the div on screen sizes small than 1536px.

**Screenshots** 

![Screen Shot 2021-06-03 at 12 04 49 PM](https://user-images.githubusercontent.com/82905787/120676412-fd92e100-c463-11eb-933e-86e99718fdf7.png)

**Comment by brittrich** [comment]
I think this is fixed, so closing, but feel free to reopen if there are any lingering issues!
