### ISSUE TITLE
UTC Highlights Block Side box bug

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/particle#356]
<img width="1329" alt="Screen Shot 2021-11-13 at 11 53 59 PM" src="https://user-images.githubusercontent.com/39039024/141668077-9743420e-9deb-449f-8f80-7caec894823e.png">
<img width="1326" alt="Screen Shot 2021-11-13 at 11 54 27 PM" src="https://user-images.githubusercontent.com/39039024/141668084-fc9d94b0-ff5f-4dcc-8475-f8794fcc6b9a.png">

The sidebox option needs some work.
It's overflowing its parent container.
@brittrich 
`    grid-template-columns: 1fr 50% 45% 1fr!important;`
i tracked it down to that.
the 50% and 45% don't seem to respect the parent container.

**Comment by bmartinez287** [comment]
Because the full width style works as expected and this won't be enable for everyone until next week. I will push it to prod and we can fix it this week.

**Comment by brittrich** [comment]
@bmartinez287 I'll take a look now!
