### ISSUE TITLE
Need to make slight adjustments to the UTC highlight

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#363]
I believe when we brought the sidebox inside the main container, it adversely affected the width of the component so that it extends outside the section frame: 

![bad-turkey-margin](https://user-images.githubusercontent.com/82905787/143299859-b84a94e9-9e36-4fce-af76-ad084466cbfd.jpg)

This can be fixed through the gridTemplateColumns found in the tailwind.config.js on line 48.

![good-turkey-margin](https://user-images.githubusercontent.com/82905787/143300105-c227074e-3baf-4b07-8940-7e370977c4a2.jpg)
 
 and full-width
 
![good-full-width-turkey-margin](https://user-images.githubusercontent.com/82905787/143300142-d8a1acf5-4cd5-44e7-a2a4-66c0413931c7.jpg)

**Comment by brittrich** [comment]
@UTCbridget this one is fixed, right?

**Comment by UTCbridget** [comment]
Yes! Thank you.
