### ISSUE TITLE
UTC Library Instruction Page Block Hover 

### ISSUE THREAD

**Issue by stevendshelton** [UTCWeb/particle#389]
Modify the yellow-glow hover effect on this page: https://www.utc.edu/library/services/instruction to match the rest of the site
![image](https://user-images.githubusercontent.com/827642/154491482-217ad778-d80a-4e7d-9401-d99195cebea1.png)

**Comment by wkominos** [comment]
Changed this in config, but am going to look into removing the option for the no-background card that results in the yellow hover.
