### ISSUE TITLE
Focus search form on search click

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/particle#397]
### Problem/Motivation
**Is your feature request related to a problem? Please describe.** 
 I'm always frustrated when I click the search icon and then have to click the search form field to begin my query. 

### Possible Solutions
**Describe the solution you'd like** 
- Clicking search icon moves focus to the search form field.
- Search Results page layout behaves same as other site pages

**Describe alternatives you've considered** 
- https://stackoverflow.com/a/57022968/1769915 (answer)
- https://stackoverflow.com/questions/57022149/move-focus-to-search-box-after-search-button-reveals-search-form (original question)

### Additional issues:
- **Skip link does not work on the Search Results page** because there is no #main-content id.
- Search Results page title is obscured by the fixed height/position header; in Admin view: logo, search icon, etc. are also obscured.
    - https://clouddev.utc.edu/search/gcse?keys=information%20technology#gsc.tab=0&gsc.q=information%20technology&gsc.sort=

![Screen Shot 2022-03-14 at 2 54 14 PM](https://user-images.githubusercontent.com/49878588/158241401-cd342fb8-a21b-4ff7-a03b-e08d84dfb2c7.png)

**Comment by UTCbridget** [comment]
These items have been address and solved.
