### ISSUE TITLE
double down triangle icons in mobile dropdown menus on Safari Mac and iOS

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/particle#405]
**Describe the bug** 
There is a double icon of the down triangle in the dropdown menus in Safari (checked via Mac, iOS Simulators and iPhone).

**To Reproduce**

1. Go to https://cloudev.utc.edu in a Safari browser, on a device with a mobile breakpoint width
2. Click on the hamburger menu

**Expected behavior** 
Down triangle icon has either default or override style, not both.

**Screenshots**
![Screen Shot 2022-03-18 at 2 32 15 PM](https://user-images.githubusercontent.com/49878588/159062883-66544e26-0232-41eb-a29e-b295e80ac6e7.png)
![Screen Shot 2022-03-18 at 2 27 33 PM](https://user-images.githubusercontent.com/49878588/159062905-deca6d8a-2241-4588-b9d3-24057fcf78f2.png)

**Desktop (please complete the following information):**

- OS:  iOS and Mac OS
- Browser Safari
- Version "latest"

**Smartphone (please complete the following information):**

- Device: iPhone11
- OS: iOS15
- Browser Safari
- Version "latest in iOS 15"

**Comment by UTCbridget** [comment]
See PR https://github.com/UTCWeb/particle/pull/413 for this fix.
