### ISSUE TITLE
META Issue for UTC Branding update improvements

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/particle#429]
Here we can gather a punch list of glitches or issues we find with visual styles, after the recent major style overhaul. Add comments below with screenshots and checklists.

- [x] Hover color on social media block in footer: changes to dark color, maybe should be yellow/gold. Poor contrast, almost looks as if it disappears on hover.
<img width="579" alt="Screen Shot 2022-04-02 at 11 19 51 AM" src="https://user-images.githubusercontent.com/49878588/161389946-f6356233-7349-4be7-8ca6-f4ae0624eea2.png">

**Comment by UTCbridget** [comment]
Yep, it's supposed to be gold. Will fix.
