### ISSUE TITLE
Active sidebar submenu button is slightly off.

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#458]
The arrow on the active sidebar submenu button is slightly off.

Other sidebar menu notes:
Hovers: Need soft transitions
Hierarchy of importance: Active parent should be gold text while its rollover siblings should be white text.

![Screen Shot 2022-05-06 at 11 25 00 AM](https://user-images.githubusercontent.com/82905787/167164115-17a7d559-44ab-4bbb-af74-5ab8ebc79862.png)

**Comment by UTCbridget** [comment]
Found another thing that needs addressing: The contrast on sub-submenus is not high enough. Bad for accessibility.
![Screen Shot 2022-05-11 at 3 39 39 PM](https://user-images.githubusercontent.com/82905787/167932280-89d62887-fd10-4353-ab83-b3563897d100.png)

**Comment by bmartinez287** [comment]
https://www.utc.edu/enrollment-management-and-student-affairs/center-for-global-education/english-second-language-institute/esl-student-life/prospective-esl-students/program-information/activities
<img width="1574" alt="Screen Shot 2022-05-22 at 12 22 43 AM" src="https://user-images.githubusercontent.com/39039024/169678544-7371e77f-1255-474a-b654-050da7380a3f.png">

**Comment by bmartinez287** [comment]
seems like this is still an issue

**Comment by bmartinez287** [comment]
The reason I used the previous colors with the navigation was mostly due to the fact they handle most child parent relationship of this type. I like this color set better but it makes it significantly more difficult to make it ADA compliant since you have to keep switching both background and font color.
