### ISSUE TITLE
UTC Video Hero

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#468]
Component library addition. Perhaps two versions: 1 with the blocked in version on duotone backgrounds like the current UTC hero, and 1 full-sized with modern floating text inside. Needs to be responsive.

**Comment by UTCWebDev** [comment]
@UTCbridget Testing the merged PR, #497  in Cloud Dev, I see the following problems:

Normal Hero background is too short:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2539685/211662173-876f026e-4d9a-49f1-a29a-2c22683f890f.png)

Mobile and narrow screens, background obscures similar colored text:
<img width="565" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/2539685/211662322-f6cdbdbb-fadf-4b4c-bb58-0f24c5a044c1.png">


Video Hero allows selection of multiple video media items:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/2539685/211662415-825f70fd-9d1a-47f0-b8a7-f35b86646b59.png)

Single YouTube video does not work:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/2539685/211662504-61a7fd93-9310-40f6-a65b-a0ac86ede17b.png)
