### ISSUE TITLE
UTC Table block... edits add blank tables.

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#535]
The UTC Table Block is adding extra tables upon editing an existing one. There is no option to remove the extra tables. Example page: https://www.utc.edu/engineering-and-computer-science/technology-symposium

**Comment by bmartinez287** [comment]
Any other info available? I think that might be coming from the TableField but I was not sure how much research has already been done about this. https://www.drupal.org/project/issues/tablefield
How critical is this? Does it block anything or goes into an infinite loop?

**Comment by UTCbridget** [comment]
As long as you enter the table perfectly the first time, it works great. It's just when you edit the table it adds another table, then another with as many edits as you make. This is editing with drag and drop OR just simply editing the text in the fields.

**Drag and drop edit:**
![Screenshot 2023-03-27 at 10 50 46 AM](https://user-images.githubusercontent.com/82905787/227996781-d97cd65a-67e2-4f13-a905-56191ca926f9.png)

**Produces this:**
![Screenshot 2023-03-27 at 12 00 09 PM](https://user-images.githubusercontent.com/82905787/227997395-f79551ed-ce32-46fb-9bbc-117ab3360aab.png)

**Front end:**
![Screenshot 2023-03-27 at 11 59 33 AM](https://user-images.githubusercontent.com/82905787/227997551-df3963e6-91e8-4151-8961-c8ef5de06a04.png)

**Comment by UTCbridget** [comment]
It doesn't block anything that I noted and it's not an infinite loop. Just extra blank tables. Annoying if you need to change anything bc you can't. You have to recreate and make sure the recreation is perfect.

**Comment by UTCGilligan** [comment]
Oh, yeah... I have experienced that problem before, so it's not new.

My workaround is to always Export Table Data, edit the CSV in local spreadsheet, export as CSV, and re-import.

**Comment by UTCGilligan** [comment]
You might want to check the issue queue for that module to see if there are any other sites experiencing the same problem.

**Comment by UTCbridget** [comment]
Yes, and I'll look.

**Comment by UTCbridget** [comment]
This is a utccloud configuration issue. [See here](https://github.com/UTCWeb/utccloud/issues/2450).

The CSS changes, however, are Particle.
