### ISSUE TITLE
The FontAwesome 5 icon is missing on the Library chat bot.

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#589]
We have removed FontAwesome 5 free version in favor of FontAwesome 6 Pro, which provides many more icons, including the Power C. This was to remove duplication and increase performance. However, The library uses FontAwesome 5 icon in its Library chat bot. 

A fix is in this file: _utclib_help_btn.css

Line 76: should be changed from
```
.lib-help__icon::before {
  font-family: 'Font Awesome 5 Free';
  font-weight: 900;
  content: '\f075';
  margin-right: 0.3rem;
}
```
to

```
.lib-help__icon::before {
  font-weight: 900;
  content: "\1F5E9";
  margin-right: 0.3rem;
}
```

**Comment by stevendshelton** [comment]
Thanks so much. This will resolve https://github.com/UTCWeb/utccloud/issues/2475

**Comment by stevendshelton** [comment]
Reopening: The icon does not display on Mac, iOS, or Android.
![image](https://github.com/UTCWeb/particle/assets/827642/49a4d8ca-ad78-4f8d-9d82-b96933eb93c7)

**Comment by UTCbridget** [comment]
It appears that on the Mac, the only unhappy camper is Safari. What are your thoughts on removing the icon altogether?

**Comment by nataliedwright** [comment]
So it shows up in chrome on the mac for you?  It doesn't for me.  It looks like it should be compatible with everything but Safari (https://developer.mozilla.org/en-US/docs/Web/CSS/::before) but it isn't.  Maybe we should just remove it since it's proving to be so problematic.

**Comment by UTCbridget** [comment]
It is in Chrome for me on the Mac. But that's what I'm thinking, too. 

If it were put into a twig file instead of CSS, we could use the <i> tag. 
We could either build on in CSS or use a jpg background image on that selector.

![Screenshot 2023-09-15 at 8 49 28 AM](https://github.com/UTCWeb/particle/assets/82905787/3611782b-ee43-4dcf-a2b5-b8569a322b5d)

**Comment by nataliedwright** [comment]
I suppose a jpg would be the one thing that would work anywhere.

**Comment by stevendshelton** [comment]
Odd that in BrowserStack, the icon is failing on all browser/OS combos on Mac, iOS, and Android I've tested. 
I think I can make this change if needed since @nataliedwright is not onboarded yet. Removing may be the easiest option for now.

**Comment by nataliedwright** [comment]
Removing is the easiest.  We can always add an icon in later if we figure out why the issue is happening.  I have been through all of my go-to tech sites, and a general google search, and I can't find an answer for why this is happening.

**Comment by stevendshelton** [comment]
@UTCbridget , I am having issues in my local Particle when running npm commands following Bernardo's documentation: https://docs.google.com/document/d/1lQHHvFbx4Y0rFRPx4EWP6pV4hs4-OlApIIq7GQVWvks Not sure if something changed. I used to run "npm run dev:drupal" and it would update changes I made to CSS. If everything has stayed the same, I'll try troubleshooting my local to see what's up.

**Comment by UTCbridget** [comment]
@stevendshelton , try `npm run build:drupal`
