### ISSUE TITLE
Library Events Block: Multi-Day enhancements - Particle

### ISSUE THREAD

**Issue by stevendshelton** [UTCWeb/particle#591]
Since they so rarely occurred, I don't think Brittany and I ever fully anticipated how multi-day events displayed in the Library Events Block (see top event in image capture on Aug. 24th):
![image](https://github.com/UTCWeb/utccloud/assets/827642/6124c385-bc66-4d9d-ad04-ecd066724260)
Multi-day events should probably grab today's date when in range (or something else?). Also, the formatting looks different from the other blocks regarding line breaks.

- [x] Fix formatting/line breaks
- [x] Modify the Date display or change it

![image](https://github.com/UTCWeb/particle/assets/827642/66d3c274-0e40-4aaf-9397-a059f39a1aef)

**Comment by nataliedwright** [comment]
In terms of the formatting, it has the span class "lib-events-box__event-time" in there twice, and one of those encloses the whole event and not just the time.  That's what's messing up the line breaks.

**Comment by stevendshelton** [comment]
> In terms of the formatting, it has the span class "lib-events-box__event-time" in there twice, and one of those encloses the whole event and not just the time. That's what's messing up the line breaks.

Thanks. I found the logic error in the Twig, so that part is an easy fix:
![image](https://github.com/UTCWeb/particle/assets/827642/5109a77f-2e05-4ecf-a189-2458c6cb56e9)
Side note: I originally built this Twig file, and Brittany tweaked it, but I definitely made the original error in the logic.

**Comment by stevendshelton** [comment]
Here's a possible solution for the other issue. Replace the date with an FA calendar-range icon:
![image](https://github.com/UTCWeb/particle/assets/827642/97e87348-f492-4980-9b80-8d7ddcbf75ac)

**Comment by nataliedwright** [comment]
I like that solution, it's a nice indicator that this event is different.
