### ISSUE TITLE
Remove body text div if no body is entered on UTC Cards.

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#639]
We need to create a condition that only shows the body text div "utc-card-2__body" if body text is present. The reason is that there is padding associated with that div that creates a blank white space under images if there is no text.

![Screenshot 2024-06-04 at 10 33 09 AM](https://github.com/UTCWeb/particle/assets/82905787/a25dcdc0-76df-40ca-8834-547257fa7422)

The variables (for each individual card) is found in this file: block--utc-card.html.twig
The condition is currently on line 89 (closing on 92), but needs to be moved to line 80 (closing on 103): block--utc-card-base.html.twig

**Comment by weston-gentry** [comment]
@UTCbridget I have a couple of questions.  

1. I'm unable to find block--utc-card-base.html.twig in my codebase. I was able to find block--utc-card.html.twig. Is it hiding from me?
2. I'm curious if we should still do this as the utc-card-2__title appears to be in utc-card-2__content (see screenshot.) In cases with a title but not a body on the block, this could be a problem (although that's probably rare.) Maybe it would be better to make the title and description fields required on the card when creating/editing the block?

![Screenshot 2024-06-24 at 3 09 49 PM](https://github.com/UTCWeb/particle/assets/64536883/07962359-ac20-4f89-ba7a-144cffbb2825)

**Comment by UTCbridget** [comment]
That's a good point. The problem I see is that some section editors use the cards with words within the image and then use the card as a link, resulting in a blank white space below the image like this: 
![Screenshot 2024-06-24 at 4 24 21 PM](https://github.com/UTCWeb/particle/assets/82905787/62943929-d5ec-450f-874a-d98b5e435fee)

So, let's try this instead of what I said above to solve both problems:

On line 48, insert this code 
```
{% elseif (card_title is empty) and (card_text is empty) %}
  {% set card_classes = [
    'utc-card-2',
    card_type ? 'utc-card-2--' ~ card_type,
    card_width ? 'utc-card-2--w-' ~ card_width,
    card_link ? 'utc-card-2--card-link',
    card_img_fill ? card_img_fill
  ] | sort | join(' ') | trim %}
```
That will change this
![Screenshot 2024-06-24 at 4 45 35 PM](https://github.com/UTCWeb/particle/assets/82905787/ce4d6a7c-e2b6-4dce-9361-2f20b2539a53)

to this, which still looks weird if one card has a headline 
![Screenshot 2024-06-24 at 4 46 15 PM](https://github.com/UTCWeb/particle/assets/82905787/1f8cb180-5e40-4bf6-b7d0-f7472a6c9876)

but not if all the cards are consistently sans headline and text.
![Screenshot 2024-06-24 at 4 46 50 PM](https://github.com/UTCWeb/particle/assets/82905787/7590a549-789f-4784-980c-0c4fbe331422)

We can hope that if they see something weird they'll change it or we can force all three cards to have the same treatment regardless of whether it's empty or not.

**Comment by UTCbridget** [comment]
This was one culprit I recently came by (though this page is no longer existent).
https://utcclouddev2.prod.acquia-sites.com/enrollment-management-and-student-affairs/pre-health-professions-advising/events/2024-pre-health-expo-events-and-information

But I've seen several like this sporadically done.

**Comment by UTCbridget** [comment]
regarding the block--utc-card-base.html.twig... It should be right above the block--utc-card.html.twig
![Screenshot 2024-06-24 at 4 20 06 PM](https://github.com/UTCWeb/particle/assets/82905787/a314a4ed-b12d-483a-bdf6-962dc8ddb144)

**Comment by weston-gentry** [comment]
Finshed. https://github.com/UTCWeb/particle/pull/646
