### ISSUE TITLE
Employee Directory Feature

### ISSUE THREAD

**Issue by Novally** [UTCWeb/particle#99]

**Comment by bmartinez287** [comment]
https://som.yale.edu/faculty-research/faculty-directory
https://www.gsb.stanford.edu/faculty-research/faculty/jennifer-lynn-aaker
https://haslam.utk.edu/experts/michel-ballings
https://michiganross.umich.edu/faculty-research/directory
https://www.sbs.ox.ac.uk/about-us/people?f%5B0%5D=department_facet%3A230
https://mitsloan.mit.edu/faculty/faculty-directory
https://haas.berkeley.edu/faculty/
